name: Hot Toys Monitor
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Run Python script
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          RSS_URL: ${{ vars.RSS_URL }}
        run: python monitor.py # <--- 直接行個 file

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add last_link.txt
          git commit -m "Update last link [skip ci]" || exit 0
          git push
